### ISSUE TITLE
[Bug] Update profile endpoint returned 500

### ISSUE THREAD

**Issue by chungthuang** [dev-launchers/strapiv4#160]
**Describe the bug**
User profiles cannot be updated because the backend returned 500 response status.

**To Reproduce**
1. Go to staging swagger API documentation
2. Try to update a profile, which sends a PUT request to https://apiv4-staging.devlaunchers.org/api/profiles/{id}
3. Received 500 response status

**Expected behavior**
The request succeed.

**Environment**
At least in staging.

**Additional context**
Sentry received an error from the update profile endpoint:
```
/srv/app/node_modules/@strapi/strapi/node_modules/@strapi/utils/dist/index.js in handleYupError at line 408:9

  PolicyError,

  RateLimitError,

  UnauthorizedError,

  ValidationError,

  YupValidationError

}, Symbol.toStringTag, { value: "Module" }));

const handleYupError = (error, errorMessage) => {

  throw new YupValidationError(error, errorMessage);

};

const defaultValidationParam = { strict: true, abortEarly: false };

const validateYupSchema = (schema, options = {}) => async (body, errorMessage) => {

  try {

    const optionsWithDefaults = fp.defaults(defaultValidationParam, options);

    const result = await schema.validate(body, optionsWithDefaults);

        return result;

/srv/app/node_modules/@strapi/strapi/node_modules/@strapi/utils/dist/index.js in <anonymous> at line 418:7
node:internal/process/task_queues in process.processTicksAndRejections at line 95:5
/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js in Object.update at line 156:23
/srv/app/node_modules/@strapi/strapi/dist/services/entity-service/index.js in Object.<anonymous> at line 309:18
/srv/app/node_modules/@strapi/strapi/dist/core-api/controller/collection-type.js in Object.update at line 68:22
/srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js in returnBodyMiddleware at line 42:18
/srv/app/node_modules/@strapi/strapi/dist/services/server/policy.js in policiesMiddleware at line 15:5
/srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js in <anonymous> at line 27:12
/srv/app/node_modules/strapi-prometheus/server/middlewares/index.js in <anonymous> at line 14:7
```

**Comment by tiagopazhs** [comment]
Just registering here another unnexpected behavio of the router `api/profiles`

### 1) `GET: api/profiles`

As you can see, my json object `response.data` is empty, but the expected is to have data because I have profiles.

![image](https://github.com/dev-launchers/strapiv4/assets/81580990/577ce2de-2c5a-43e1-bcde-32c221d7aeb7)

In addition to this, follow the print of the `get: api/profiles/2`

![image](https://github.com/dev-launchers/strapiv4/assets/81580990/d63cdf18-cd6b-4543-b1c6-72c3b21089d6)

### 2) `PUT: api/profiles/:id`

The issue for itself:

When I try to reproduce this error, I am geting a status code 400 about some permitions, but I didn't got the 500, is there something to add ?

![image](https://github.com/dev-launchers/strapiv4/assets/81580990/aec44ba7-ad1e-477f-b381-99b37476f2e7)

Observation:  I am using my local server as {{base_url}}


### 3) Some tests using interface.

When I try to update my bio in devlauchers platform I am getting a 405 status code:

`LOCAL:`
![image](https://github.com/dev-launchers/strapiv4/assets/81580990/b8cfd829-5fa4-4cae-a5bb-e7d4319a080e)

`PRODUCTION:`
![image](https://github.com/dev-launchers/strapiv4/assets/81580990/9e77c1f2-076c-416e-a867-d40f6dba1cb6)

**Comment by chungthuang** [comment]
@tiagopazhs I tried again and this time I see a different error in strapi log
```
[2024-04-04 03:38:58.785] [31merror[39m: Forbidden access
ForbiddenError: Forbidden access
at Object.verify (/srv/app/node_modules/@strapi/plugin-users-permissions/server/strategies/users-permissions.js:106:11)
at Object.verify (/srv/app/node_modules/@strapi/strapi/dist/services/auth/index.js:75:30)
at /srv/app/node_modules/@strapi/strapi/dist/services/server/compose-endpoint.js:26:23
at dispatch (/srv/app/node_modules/koa-compose/index.js:42:32)
at Object.authenticate (/srv/app/node_modules/@strapi/strapi/dist/services/auth/index.js:62:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /srv/app/node_modules/strapi-prometheus/server/middlewares/index.js:14:7
at async /srv/app/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js:19:7
at async /srv/app/src/extensions/users-permissions/server/middlewares/jwt.js:12:5
```
The payload was
```
{
  "data": {
    "bio": "about me"
  }
}
```
The problem is the swagger documentation calls the API as an unauthenticated user. Once I gave the unauthenticated user permission to call the update profile endpoint, I got a successful response.

**Comment by chungthuang** [comment]
I think we can close this issue because the problem is swagger documentation calls the API as an unauthenticated user.
