### ISSUE TITLE
[Bug] Can't request the notifications for the logged-in user, all notifications are served.

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/strapiv4#161]
**Describe the bug**
Currently all notifications (from any user) are returned from `/api/notifications` endpoint, that endpoint should only return notifications for the logged in user only.

**To Reproduce**
1. GET request to `/api/notifications`
2. See many notifications that aren't related to the current logged in user.

**Expected behavior**
The endpoint only returning notifications for the logged in user.

**Comment by becevka** [comment]
To sum up from the Discord discussion, I suggest to consider the following:
Notifications are in essence events describing how specific entity was updated, for example, idea was updated, new comment posted to idea, etc.
Binding notifications to the recipient user is limiting.
Instead we need to allow search for notifications based on entityType and entityId. 
This means instead of expecting to call /api/notifications?filters[recipient][$eq]=5, we should call /api/notifications?filters[entityType][$eq]= IdeaCard&filters[entityId][$in][0]=1&filters[entityId][$in][1]=5.
This will allow dynamically select notifications to the user based on additional logic.

@chungthuang @Enjoy2Live I think this correlates to your discussion in original Notification implementation PR https://github.com/dev-launchers/strapiv4/pull/103#discussion_r1429181885

**Comment by Enjoy2Live** [comment]
@becevka Thanks for the detailed response!

Notifications to me seem targeted to users specifically, what you mentioned in the first bullet point seem like "Events" CollectionType that we may add in the future if needed and can be used as monitoring collection or to send webhooks somewhere etc.

> This will allow dynamically select notifications to the user based on additional logic.

How's that additional logic gonna look like?

I'm assuming we would create that "Events" collection and make it monitor all operations and Product teams can use it anywhere they please without worrying about "recipient" field.
And of course if they wanted to opt in to the "Notifications" which are bind to registered users they can too.

**Comment by becevka** [comment]
As we have Notification System epic which will cover the main request, we can close this ticket.
