### ISSUE TITLE
[Bug] User can call /user/id API and access other user data

### ISSUE THREAD

**Issue by becevka** [dev-launchers/strapiv4#179]
**Describe the bug**

**To Reproduce**
1. Login to strapi using '/api/auth/local' and test user with id 1,  'tester'
2. Go to /api/users/2
3. User details are returned with response code 200

**Expected behavior**
Response code 403 or other error not allowing to get another user details

**ACCEPTANCE CRITERIA**
- PII is restricted to the currently authenticated user
- The IdeaSpace workshopping page no longer displays PII (current displays users' emails)
- The IdeaSpace comments no longer displays PII (currently displays users' full names)

**Comment by becevka** [comment]
Good read https://stackoverflow.com/questions/74728231/why-all-users-in-strapi-have-access-to-update-all-users-profile

**Comment by becevka** [comment]
- We will need to enable this as we should be able to access profiles of users who posted comment, or created notifications.
- The solution would be to add a middleware to select only configured fields in user and profile collection.

**Comment by dbradham** [comment]
@chadcrotchett @chungthuang currently, user names and emails are displayed on the idea workshopping page. If this change is merged, IdeaSpace would need to update this page.

Chad, does it sound okay to you if we make a ticket in Platform board to use the display name instead of the emails or full legal names on the Idea Workshopping page? Or do you want this change to be made by the IdeaSpace team?

![Image](https://github.com/user-attachments/assets/4a35c102-4531-48ab-bca5-6fbbc21c6f89)


![Image](https://github.com/user-attachments/assets/3abd724c-92a9-4660-84ce-9f9ad536095e)

**Comment by chadcrotchett** [comment]
I'd like to remove PII, such as email and full name....so, I think that's
what you are offering, right?

I'm on my phone now - but if you can send a screenshot of what it will look
like after the merge I could glance at it.

Thanks,

Chad

**Comment by dbradham** [comment]
@chadcrotchett yes, we can remove PII from the Workshopping page.

- Instead of displaying the user's full name on the comments, we will update to show their display name
- Instead of displaying the user's email on the workshopping page, we will update to show their display name

**Comment by chadcrotchett** [comment]
Sounds great!
